plugins {
    id "com.android.application"
}

android {
    namespace "kr.ieum.smsgateway"
    compileSdk 35

    defaultConfig {
        applicationId "kr.ieum.smsgateway"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.2.0"
    }
}

afterEvaluate {
    tasks.register("copyDebugApkToWeb", Copy) {
        from(layout.buildDirectory.file("outputs/apk/debug/app-debug.apk"))
        into(file("../../assets/apps"))
        rename { "ieum-sms-gateway-debug.apk" }
    }

    tasks.named("assembleDebug").configure {
        finalizedBy("copyDebugApkToWeb")
    }
}
